version: "3.3"
services:
  az-edu:
    image: zzsure/az-edu:1.0.0
    container_name: az-edu-${USER}
    network_mode: "host"
    working_dir: /root/deploy/az-edu
    volumes:
      - "/root/deploy/az-edu/config.toml:/root/deploy/az-edu/config.toml"
    restart: always
    entrypoint:
      - /root/deploy/az-edu/az-edu
      - server
      - -c
      - /root/deploy/az-edu/config.toml
